services:
  - type: web
    name: hands-and-hope-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://handsandhope_user:B4yxG7yaMScYhKG5@backendcl.3t9sjut.mongodb.net/?appName=backendCl
      - key: JWT_SECRET
        value: your_jwt_secret_key_here
      - key: PORT
        value: 5000

  - type: web
    name: hands-and-hope-buyers
    env: static
    buildCommand: cd Buyers && npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://handsandhope.onrender.com
      - key: REACT_APP_ELEVEN_LABS_API_KEY
        value: sk_20734ae2903209818628e37d95e46a5c6f59a503a17d1eb3
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: hands-and-hope-sellers
    env: static
    buildCommand: cd Sellers && npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://handsandhope.onrender.com
      - key: REACT_APP_ELEVEN_LABS_API_KEY
        value: sk_20734ae2903209818628e37d95e46a5c6f59a503a17d1eb3
    routes:
      - type: rewrite
        source: /*
        destination: /index.html