services:
  buyers-frontend:
    build: .
    container_name: hands_and_hope_buyers_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://host.docker.internal:5000
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules